### ISSUE TITLE
Preprocessing with artifact detection, SSP and ICA

### ISSUE THREAD

**Issue by rrossyrrossy** [mctosima/EDF-Processor#1]
[https://www.youtube.com/watch?v=sttf-Rgfl1Q&ab_channel=NeuralOscillations](url)
Before: 15:10- After 22:05 

Preprocessing with artifact detection, SSP and ICA- 15:38
can mark bad channel?

**Comment by mctosima** [comment]
Yes it is. However, ICA is a machine learning technique. But I can implement it later. Not a big deal.
